spring:
  application.name: microservice-hystrix-turbine
server:
  port: 8031
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-customer-moive-fegin-with-hystrix
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/